### ISSUE TITLE
can't test kmemcache

### ISSUE THREAD

**Issue by pipul** [Qihoo360/kmemcache#5]
[root@localhost kmemcache]# ./test/testapp 
1..41
ok 1 - strtol
ok 2 - strtoll
ok 3 - strtoul
ok 4 - strtoull
insmod: can't read './kmod/kmemcache': No such file or directory
testapp: util.c:53: insert_kmod: Assertion `stat == 0' failed.
testapp: testapp.c:286: start_server: Assertion`stat == 0' failed.
Aborted

**Comment by jgli** [comment]
fixed
